### ISSUE TITLE
Homs installation error: Migration problem

### ISSUE THREAD

**Issue by Pdh362** [latera/homs#16]
Hi - Trying out the installation, hit a problem at the last stage when trying the Hom migration stage 'bundle exec rake db:migrate'. Output is 

```
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `print_form_code=' for #<OrderType:0x0000000416c750>/home/XXXX/.rvm/gems/ruby-2.2.4@homs/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/paulh/homs/app/models/order_type.rb:74:in `parse_file'
/home/paulh/homs/app/models/order_type.rb:32:in `initialize'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:61:in `new'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:61:in `new'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/persistence.rb:50:in `create!'
/home/paulh/homs/db/migrate/20160328094110_add_initial_order_types.rb:115:in `block in change'
/home/paulh/homs/db/migrate/20160328094110_add_initial_order_types.rb:114:in `each'
/home/paulh/homs/db/migrate/20160328094110_add_initial_order_types.rb:114:in `change'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/bundle:23:in `load'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/bundle:23:in `<main>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/ruby_executable_hooks:15:in `eval'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `print_form_code=' for #<OrderType:0x0000000416c750>
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/paulh/homs/app/models/order_type.rb:74:in `parse_file'
/home/paulh/homs/app/models/order_type.rb:32:in `initialize'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:61:in `new'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:61:in `new'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/persistence.rb:50:in `create!'
/home/paulh/homs/db/migrate/20160328094110_add_initial_order_types.rb:115:in `block in change'
/home/paulh/homs/db/migrate/20160328094110_add_initial_order_types.rb:114:in `each'
/home/paulh/homs/db/migrate/20160328094110_add_initial_order_types.rb:114:in `change'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/bundle:23:in `load'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/bundle:23:in `<main>'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/ruby_executable_hooks:15:in `eval'
/home/paulh/.rvm/gems/ruby-2.2.4@homs/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sugarfree1** [comment]
Hi, @Pdh362 



Thanks for the pull request. We reproduced the problem.

There is a workaround for that:
- checkout to 84b98eb44c338c6874d03429d998dc12225e77c2
```
git checkout 84b98eb44c338c6874d03429d998dc12225e77c2
```

- run migrations
```
bundle exec rake db:migrate
```

- checkout to master
```
git checkout master
```

- finish migrations
```
bundle exec rake db:migrate
```

**Comment by Pdh362** [comment]
Many thanks for the prompt response - workaround succeeded, software appears to be running fine now.

**Comment by sugarfree1** [comment]
Problem solved in https://github.com/latera/homs/pull/17
