### ISSUE TITLE
"500 Internal Server Error" на localhost:3000 после установки 

### ISSUE THREAD

**Issue by sergzykov** [latera/homs#321]
It was done according to the instructions in readme.md. PostgreSQL is used as the database.

The user manual was about a.

```
1. Install docker-compose.

2. Clone HOMS git repository:
git clone https://github.com/latera/homs.git
    
3. Skipped (used Debian 9)

4. Copy your (or default) .env file to your project's directory:
cp .env.sample .env
All variables are set in .env file. There you can change them, if you want to.

4.1. Create your own configs from samples:
find config -name '*.sample' | xargs -I{} sh -c 'cp $1 ${1%.*}' -- {}

5. Add SECRET_KEY_BASE variable to your .env with uniq id as value. Generate it any way you like. For example:
SECRET_KEY_BASE=0750fd0eac13032778f0a42e2ab450003eaece477ea881501be0cc438f870a2f498dbbc00ffb7c8379c30c960568a402d315496bb7bc2b3ee324401ba788a
Make sure this key is secret and don't share it with anyone.

5.1. Place the downloaded Oracle Instant Client RPMs in the same directory as the Dockerfile and run:
docker build -t latera/homs .

6. Skip this step

7. Be sure to update secret key in /etc/hydra/homs/secrets.yml. You can generate key with this command:
openssl rand -hex 64

8. Run docker-compose: with custom config:
docker-compose -f docker-compose.dev.yml up -d

9. Navigate to Minio control panel and create a bucket with name equal to MINIO_BUCKET_NAME value from .env file.

10. Navigate to Camunda Admin and create admin user with credentials equal to BPM_USER:BPM_PASSWORD values from .env file.

11. (Optional) If you want to use demo processes navigate to Camunda and create user with user@example.com email.

12. Login at HydraOMS with user@example.com/changeme
```

Maybe some extra step. Although normally the base stood all in /opt/homs/data all appeared and error on connecting in the logs of the containers are not see. 
But perhaps on the contrary something is missing yet, because the last step gives the browser the following:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

And the log in the container contains this:
```
[HOMS] I, [2019-07-30T07:13:36.302987 #32]  INFO -- : Started GET "/users/sign_in" for 10.25.0.151 at 2019-07-30 07:13:36 +0000
[HOMS] I, [2019-07-30T07:13:36.308997 #32]  INFO -- : Processing by SessionsController#new as HTML
[HOMS] I, [2019-07-30T07:13:36.437369 #32]  INFO -- :   Rendering devise/sessions/new.html.erb within layouts/application
[HOMS] I, [2019-07-30T07:13:36.448445 #32]  INFO -- :   Rendered devise/sessions/new.html.erb within layouts/application (10.6ms)
[HOMS] I, [2019-07-30T07:13:36.464234 #32]  INFO -- : Completed 500 Internal Server Error in 155ms (ActiveRecord: 18.4ms)
[HOMS] F, [2019-07-30T07:13:36.465703 #32] FATAL -- :
[HOMS] F, [2019-07-30T07:13:36.465909 #32] FATAL -- : ActionView::Template::Error (Webpacker can't find hbw in /opt/homs/public/assets/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
[HOMS] F, [2019-07-30T07:13:36.466532 #32] FATAL -- :      6:     %meta{ name: 'description', content: "#{content_for?(:description) ? yield(:description) : 'Homs'}"}
     7:     = stylesheet_link_tag 'hbw', media: 'all'
     8:     = stylesheet_link_tag 'application', media: 'all'
     9:     = javascript_pack_tag 'hbw'
    10:     = javascript_pack_tag 'application'
    11:     = csrf_meta_tags
    12:   %body.hbw-select2
[HOMS] F, [2019-07-30T07:13:36.466867 #32] FATAL -- :
[HOMS] F, [2019-07-30T07:13:36.467075 #32] FATAL -- : app/views/layouts/application.html.haml:9:in `_app_views_layouts_application_html_haml___3385143447312368567_46958467698660'
config/unicorn.rb:20:in `process_client'
```

It is not clear where the container is trying to access the system folder /opt/homs/public/assets/packs or inside the container. There is such a folder inside the container, because docker build was made.

Help to understand that already to test this system.

**Comment by TimAle** [comment]
Hello, @sergzykov !
It looks like `docker-compose.dev.yml` is broken, thank you for reporting!
You can use `docker-compose.yml`, it should be quite enough for app testing.

Also I'd like to ask you to use English in this conversation.

**Comment by sergzykov** [comment]
> Also I'd like to ask you to use English in this conversation.
Sorry, ok.

I used `docker-compose.yml` and everything worked. Thanks

**Comment by sergzykov** [comment]
Everything seems to have started. But after login (user@examples.com/changeme) on the main page I see a list of orders and after clicking on any of them I see an error 500 and partial order data.
We will continue to see what may be wrong.

Here is the HOMS container log.

```
[HOMS] I, [2019-07-30T11:45:02.856446 #25]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:02 +0000
[HOMS] I, [2019-07-30T11:45:02.859288 #25]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:02.859524 #25]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:02.866114 #25]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:02.875707 #25]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:02.876833 #25]  INFO -- : Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.8ms)
[HOMS] F, [2019-07-30T11:45:02.878320 #25] FATAL -- :
[HOMS] F, [2019-07-30T11:45:02.878580 #25] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:02.878825 #25] FATAL -- :
[HOMS] F, [2019-07-30T11:45:02.879081 #25] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:07.123216 #37]  INFO -- : Started GET "/orders" for 10.25.0.151 at 2019-07-30 11:45:07 +0000
[HOMS] I, [2019-07-30T11:45:07.156096 #37]  INFO -- : Processing by OrdersController#index as HTML
[HOMS] I, [2019-07-30T11:45:07.497327 #37]  INFO -- :   Rendering orders/index.html.haml within layouts/application
[HOMS] I, [2019-07-30T11:45:07.530596 #37]  INFO -- :   Rendered orders/_search_by.html.haml (2.8ms)
[HOMS] I, [2019-07-30T11:45:07.532001 #37]  INFO -- :   Rendered orders/_search_by.html.haml (0.7ms)
[HOMS] I, [2019-07-30T11:45:07.811000 #38]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:07 +0000
[HOMS] I, [2019-07-30T11:45:07.813956 #38]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:07.814288 #38]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:07.820841 #38]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:07.839339 #38]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:07.840165 #38]  INFO -- : Completed 500 Internal Server Error in 26ms (ActiveRecord: 0.7ms)
[HOMS] F, [2019-07-30T11:45:07.841271 #38] FATAL -- :
[HOMS] F, [2019-07-30T11:45:07.841349 #38] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:07.841531 #38] FATAL -- :
[HOMS] F, [2019-07-30T11:45:07.841764 #38] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:07.964251 #37]  INFO -- :   Rendered orders/_filter_by.html.haml (431.1ms)
[HOMS] I, [2019-07-30T11:45:07.964687 #37]  INFO -- :   Rendered orders/_search_form.html.haml (461.8ms)
[HOMS] I, [2019-07-30T11:45:07.995444 #37]  INFO -- :   Rendered orders/index.html.haml within layouts/application (497.9ms)
[HOMS] I, [2019-07-30T11:45:08.210852 #37]  INFO -- :   Rendered layouts/_navigation.html.haml (2.1ms)
[HOMS] I, [2019-07-30T11:45:08.617541 #37]  INFO -- : Completed 200 OK in 1461ms (Views: 1116.5ms | ActiveRecord: 14.3ms)
[HOMS] I, [2019-07-30T11:45:09.179890 #38]  INFO -- : Started GET "/orders/list?controller=orders&action=index&page_size=25&page=1&sort_by=&order=asc" for 10.25.0.151 at 2019-07-30 11:45:09 +0000
[HOMS] I, [2019-07-30T11:45:09.182430 #38]  INFO -- : Processing by OrdersController#list as JSON
[HOMS] I, [2019-07-30T11:45:09.182707 #38]  INFO -- :   Parameters: {"page_size"=>"25", "page"=>"1", "sort_by"=>"", "order"=>"asc"}
[HOMS] I, [2019-07-30T11:45:09.198736 #37]  INFO -- : Started GET "/widget/users/check" for 10.25.0.151 at 2019-07-30 11:45:09 +0000
[HOMS] I, [2019-07-30T11:45:09.200870 #37]  INFO -- : Processing by HBW::UsersController#check_user as JSON
 [HBW] I, [2019-07-30T11:45:09.207157 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:09.228964 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:09.229944 #37]  INFO -- : Completed 500 Internal Server Error in 29ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:09.231376 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:09.231598 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:09.231842 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:09.232051 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:09.249586 #38]  INFO -- :   Rendering orders/list.json.erb
[HOMS] I, [2019-07-30T11:45:09.258911 #38]  INFO -- :   Rendered orders/list.json.erb (9.1ms)
[HOMS] I, [2019-07-30T11:45:09.259416 #38]  INFO -- : Completed 200 OK in 76ms (Views: 24.5ms | ActiveRecord: 2.0ms)
[HOMS] I, [2019-07-30T11:45:09.409950 #37]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:09 +0000
[HOMS] I, [2019-07-30T11:45:09.411660 #37]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:09.411883 #37]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:09.416804 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:09.424535 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:09.425485 #37]  INFO -- : Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:09.426795 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:09.427039 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:09.427231 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:09.427491 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:14.438672 #37]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:14 +0000
[HOMS] I, [2019-07-30T11:45:14.440389 #37]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:14.440624 #37]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:14.445748 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:14.458376 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:14.458993 #37]  INFO -- : Completed 500 Internal Server Error in 18ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:14.459928 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:14.460113 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:14.460247 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:14.460429 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:19.423668 #32]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:19 +0000
[HOMS] I, [2019-07-30T11:45:19.425739 #32]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:19.425934 #32]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:19.432625 #32]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:19.443123 #32]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:19.444289 #32]  INFO -- : Completed 500 Internal Server Error in 18ms (ActiveRecord: 0.8ms)
[HOMS] F, [2019-07-30T11:45:19.445745 #32] FATAL -- :
[HOMS] F, [2019-07-30T11:45:19.446018 #32] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:19.446120 #32] FATAL -- :
[HOMS] F, [2019-07-30T11:45:19.446306 #32] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:26.944214 #37]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:26 +0000
[HOMS] I, [2019-07-30T11:45:26.945769 #37]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:26.946036 #37]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:26.951060 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:26.960859 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:26.961772 #37]  INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:26.963061 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:26.963340 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:26.963532 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:26.963755 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:29.427286 #37]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:29 +0000
[HOMS] I, [2019-07-30T11:45:29.428929 #37]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:29.429154 #37]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:29.433648 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:29.442563 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:29.443537 #37]  INFO -- : Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:29.445006 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:29.445189 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:29.445443 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:29.445629 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:34.426598 #25]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:34 +0000
[HOMS] I, [2019-07-30T11:45:34.428409 #25]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:34.428600 #25]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:34.433986 #25]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:34.441441 #25]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:34.442685 #25]  INFO -- : Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.8ms)
[HOMS] F, [2019-07-30T11:45:34.444083 #25] FATAL -- :
[HOMS] F, [2019-07-30T11:45:34.444191 #25] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:34.444308 #25] FATAL -- :
[HOMS] F, [2019-07-30T11:45:34.444412 #25] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:39.418531 #37]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:39 +0000
[HOMS] I, [2019-07-30T11:45:39.420212 #37]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:39.420332 #37]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:39.425361 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:39.432084 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:39.432825 #37]  INFO -- : Completed 500 Internal Server Error in 12ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:39.433898 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:39.433973 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:39.434057 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:39.434206 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:44.424804 #33]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:44 +0000
[HOMS] I, [2019-07-30T11:45:44.427952 #33]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:44.428315 #33]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:44.435206 #33]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:44.446171 #33]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:44.447482 #33]  INFO -- : Completed 500 Internal Server Error in 19ms (ActiveRecord: 0.7ms)
[HOMS] F, [2019-07-30T11:45:44.449027 #33] FATAL -- :
[HOMS] F, [2019-07-30T11:45:44.449261 #33] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:44.449551 #33] FATAL -- :
[HOMS] F, [2019-07-30T11:45:44.449815 #33] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:49.446122 #37]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:49 +0000
[HOMS] I, [2019-07-30T11:45:49.447758 #37]  INFO -- : Processing by HBW::TasksController#index as JSON
[HOMS] I, [2019-07-30T11:45:49.447880 #37]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:49.452929 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:49.463935 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:49.464700 #37]  INFO -- : Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:49.465908 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:49.466012 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:49.466095 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:49.466183 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:51.701198 #37]  INFO -- : Started GET "/orders/ORD-3" for 10.25.0.151 at 2019-07-30 11:45:51 +0000
[HOMS] I, [2019-07-30T11:45:51.703179 #37]  INFO -- : Processing by OrdersController#show as HTML
[HOMS] I, [2019-07-30T11:45:51.703298 #37]  INFO -- :   Parameters: {"id"=>"ORD-3"}
[HOMS] I, [2019-07-30T11:45:51.713742 #37]  INFO -- :   Rendering orders/show.html.haml within layouts/application
[HOMS] I, [2019-07-30T11:45:51.759885 #37]  INFO -- :   Rendered orders/_common.html.haml (13.8ms)
[HOMS] I, [2019-07-30T11:45:51.760052 #37]  INFO -- :   Rendered orders/_data.html.haml (20.2ms)
[HOMS] I, [2019-07-30T11:45:51.760211 #37]  INFO -- :   Rendered orders/show.html.haml within layouts/application (46.3ms)
[HOMS] I, [2019-07-30T11:45:51.957679 #37]  INFO -- :   Rendered layouts/_navigation.html.haml (2.1ms)
[HOMS] I, [2019-07-30T11:45:52.384362 #37]  INFO -- : Completed 200 OK in 681ms (Views: 670.9ms | ActiveRecord: 2.1ms)
[HOMS] I, [2019-07-30T11:45:52.704547 #30]  INFO -- : Started GET "/widget/users/check" for 10.25.0.151 at 2019-07-30 11:45:52 +0000
[HOMS] I, [2019-07-30T11:45:52.706216 #30]  INFO -- : Processing by HBW::UsersController#check_user as JSON
 [HBW] I, [2019-07-30T11:45:52.711420 #30]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:52.720777 #30]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:52.721701 #30]  INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:52.723072 #30] FATAL -- :
[HOMS] F, [2019-07-30T11:45:52.723217 #30] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:52.723480 #30] FATAL -- :
[HOMS] F, [2019-07-30T11:45:52.723721 #30] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:52.842286 #37]  INFO -- : Started GET "/widget/buttons?entity_code=ORD-3&entity_type=pizza_order&entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:52 +0000
[HOMS] I, [2019-07-30T11:45:52.844034 #37]  INFO -- : Processing by HBW::ButtonsController#index as JSON
[HOMS] I, [2019-07-30T11:45:52.844161 #37]  INFO -- :   Parameters: {"entity_code"=>"ORD-3", "entity_type"=>"pizza_order", "entity_class"=>"order"}
[HOMS] I, [2019-07-30T11:45:52.847592 #33]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:52 +0000
[HOMS] I, [2019-07-30T11:45:52.849202 #33]  INFO -- : Processing by HBW::TasksController#index as JSON
 [HBW] I, [2019-07-30T11:45:52.849527 #37]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
[HOMS] I, [2019-07-30T11:45:52.849568 #33]  INFO -- :   Parameters: {"entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:52.855963 #33]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:52.858086 #37]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:52.859110 #37]  INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.5ms)
[HOMS] F, [2019-07-30T11:45:52.860557 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:52.861330 #37] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:52.861456 #37] FATAL -- :
[HOMS] F, [2019-07-30T11:45:52.861680 #37] FATAL -- : config/unicorn.rb:20:in `process_client'
 [HBW] W, [2019-07-30T11:45:52.866325 #33]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:52.867407 #33]  INFO -- : Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.8ms)
[HOMS] F, [2019-07-30T11:45:52.868839 #33] FATAL -- :
[HOMS] F, [2019-07-30T11:45:52.869146 #33] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:52.869325 #33] FATAL -- :
[HOMS] F, [2019-07-30T11:45:52.869733 #33] FATAL -- : config/unicorn.rb:20:in `process_client'
[HOMS] I, [2019-07-30T11:45:57.872611 #33]  INFO -- : Started GET "/widget/buttons?entity_code=ORD-3&entity_type=pizza_order&entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:57 +0000
[HOMS] I, [2019-07-30T11:45:57.874174 #33]  INFO -- : Processing by HBW::ButtonsController#index as JSON
[HOMS] I, [2019-07-30T11:45:57.874289 #33]  INFO -- :   Parameters: {"entity_code"=>"ORD-3", "entity_type"=>"pizza_order", "entity_class"=>"order"}
 [HBW] I, [2019-07-30T11:45:57.879720 #33]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
[HOMS] I, [2019-07-30T11:45:57.888092 #30]  INFO -- : Started GET "/widget/tasks?entity_class=order" for 10.25.0.151 at 2019-07-30 11:45:57 +0000
[HOMS] I, [2019-07-30T11:45:57.890130 #30]  INFO -- : Processing by HBW::TasksController#index as JSON
 [HBW] W, [2019-07-30T11:45:57.890402 #33]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:57.890420 #30]  INFO -- :   Parameters: {"entity_class"=>"order"}
[HOMS] I, [2019-07-30T11:45:57.891165 #33]  INFO -- : Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.7ms)
[HOMS] F, [2019-07-30T11:45:57.892405 #33] FATAL -- :
[HOMS] F, [2019-07-30T11:45:57.892510 #33] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:57.892593 #33] FATAL -- :
[HOMS] F, [2019-07-30T11:45:57.892679 #33] FATAL -- : config/unicorn.rb:20:in `process_client'
 [HBW] I, [2019-07-30T11:45:57.896589 #30]  INFO -- : GET http://camunda:8080/engine-rest/user?email=user%40example.com
 [HBW] W, [2019-07-30T11:45:57.900824 #30]  WARN -- : HTTP 401
[HOMS] I, [2019-07-30T11:45:57.901405 #30]  INFO -- : Completed 500 Internal Server Error in 10ms (ActiveRecord: 0.4ms)
[HOMS] F, [2019-07-30T11:45:57.902369 #30] FATAL -- :
[HOMS] F, [2019-07-30T11:45:57.902446 #30] FATAL -- : HBW::Remote::RemoteError (Failed to make a request to user (Failed to make a request to user (response code: 401, body: ))):
[HOMS] F, [2019-07-30T11:45:57.902505 #30] FATAL -- :
[HOMS] F, [2019-07-30T11:45:57.902566 #30] FATAL -- : config/unicorn.rb:20:in `process_client'
```

**Comment by TimAle** [comment]
It looks like HOMS can't authenticate to Camunda.

Are you sure you performed step 10 properly?

* Navigate to [Camunda Admin](http://localhost:8080/camunda) and create admin user with credentials equal to `BPM_USER:BPM_PASSWORD` values from `.env` file.

**Comment by sergzykov** [comment]
Maybe not. I'll try again.

**Comment by sergzykov** [comment]
I created a user in camunda according to `bpm_user:bpm_password` from an env file, but with a different email. Has got also a test user with email `user@example.com` and it worked.
Thank you, everything seems to be working properly.

**Comment by davidmroth** [comment]
And don't forget to add the bpm_user:bpm_password into the "camunda-admin" in the Camunda admin tool.
