### ISSUE TITLE
Error "Migrations are pending." while trying to  navigate to localhost:3000 after launching using docker-compose

### ISSUE THREAD

**Issue by balajicv** [latera/homs#80]
![image](https://user-images.githubusercontent.com/5955402/36338351-2becc530-1372-11e8-9df7-38d5e4ce1c20.png)

Trace 

activerecord (4.2.7.1) lib/active_record/migration.rb:392:in `check_pending!'
activerecord (4.2.7.1) lib/active_record/migration.rb:373:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:31:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.7.1) lib/rails/rack/logger.rb:22:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.8) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
railties (4.2.7.1) lib/rails/application.rb:165:in `call'
thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.4) lib/thin/connection.rb:84:in `catch'
thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
eventmachine (1.2.0.1) lib/eventmachine.rb:1076:in `call'
eventmachine (1.2.0.1) lib/eventmachine.rb:1076:in `block in spawn_threadpool'

**Comment by balajicv** [comment]
while I run the docker-compose, the app didnt navigate to login page rather display this error page.

**Comment by balajicv** [comment]
After running the bin/rake command, i get the app navigating to login. Should be a pull request to add this command as part of the docker-compose  to run at startup ?

**Comment by balajicv** [comment]
I see the entrypoint.sh runs the command as part of the startup, hence closing this issues.
